[versions]
kotlin = "1.7.20"
composeCompiler = "1.3.2"
hilt = "2.44"
appcompat = "1.5.1"
material = "1.8.0-alpha02"
lifecycle = "2.5.1"
retrofit2 = "2.9.0"
room = "2.4.3"
landscapist = "2.1.11"

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version = "7.3.1" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
google-services = { group = "com.google.gms", name = "google-services", version = "4.3.14" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-composeThemeAdapter = { group = "com.google.android.material", name = "compose-theme-adapter", version = "1.1.20" }
material3-composeThemeAdapter = { group = "com.google.android.material", name = "compose-theme-adapter-3", version = "1.0.21" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.9.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.5.6" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.2.1" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version = "1.0.0" }
androidx-browser = { group = "androidx.browser", name = "browser", version = "1.4.0" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version = "3.1.1" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.6.1" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.2.1" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version = "1.4.1" }
androidx-compose_material = { group = "androidx.compose.material", name = "material", version = "1.3.1" }
androidx-compose_material3 = { group = "androidx.compose.material3", name = "material3", version = "1.0.0" }

androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version = "2.2.0" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-gradle = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.6.1" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version = "1.6.4" }

firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx", version = "21.2.0" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version = "21.2.1" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version = "24.4.1" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version = "21.3.0" }

retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
okhttp3-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version = "4.10.0" }

inject = { group = "javax.inject", name = "javax.inject", version = "1" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.9.1" }

landscapist-glide = { group = "com.github.skydoves", name = "landscapist-glide", version.ref = "landscapist" }
landscapist-animation = { group = "com.github.skydoves", name = "landscapist-animation", version.ref = "landscapist" }

mlkit-imageLabeling = { group = "com.google.mlkit", name = "image-labeling", version = "17.0.7" }

playServices-auth = { group = "com.google.android.gms", name = "play-services-auth", version = "20.2.0" }
playServices-ossLicenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version = "17.0.0" }
ossLicenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version = "0.10.6" }

[bundles]
retrofit2 = ["retrofit2", "retrofit2-converter-gson", "okhttp3-logging"]
