name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
        
    - name: Create key file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "app/PhotosGitHubKey"
        FILE_DATA: ${{ secrets.DEV_KEY }}
        
    - name: Create keystore.properties
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "keystore.properties"
        FILE_DATA: ${{ secrets.DEV_KEYSTORE_PROPERTIES }}
        
    - name: Update keys.c
      run: echo '${{ secrets.DEV_KEYS }}' > app/src/main/jni/keys.c
      
    - name: Create google-services.json
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "app/google-services.json"
        FILE_DATA: ${{ secrets.DEV_GOOGLE_SERVICES }}
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDevRelease
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: photos-dev-release.apk
        path: app/build/outputs/apk/dev/release/app-dev-release.apk
